### PR TITLE
Fixes exception, thrown in Safari 7 on iPad

### LINKED ISSUE #190: Mobile Safari 7 fails with exception when trying to define `baseURI` property on `doc`
screen shot 2015-02-09 at 3 02 30 pm

Reproducible on an iPad w/ iOs7

### PR DESCRIPTION
**Pull request by mereskin**
fixes #190

### CODE REVIEW

**Comment by jmesserly** [comment]
I tend to think of try+catch as a last resort ... I wonder if we can figure out if it will throw before calling it. Does Object.getOwnPropertyDescriptor(doc, 'baseURI') return something useful? (where `doc` is one of: document, HTMLDocument.prototype, Document.prototype). What about `document.baseURI`?

**Comment by mereskin** [comment]
I'll check tomorrow.

**Comment by mereskin** [comment]
In Safari 7 `baseURI` accessor is already defined on document and is not configurable. I updated conditional and now tests pass in Safari 7.

IE11 has 3 failing tests, but they also fail on master. I don't have IE10 VM handy.

File: src/HTMLImports/importer.js [hunk 1]
```diff
@@ -128,7 +132,7 @@ function makeDocument(resource, url) {
   var base = doc.createElement('base');
   base.setAttribute('href', url);
   // add baseURI support to browsers (IE) that lack it.
-  if (!doc.baseURI) {
+  if (!hasBaseURIAccessor(doc)) {
```
Comment (jmesserly) [inline src/HTMLImports/importer.js]: I wonder if we should keep both checks here? In other words:
```js
  if (!doc.baseURI && !Object.hasOwnProperty(doc, 'baseURI')) {
```

(also can use hasOwnProperty instead of getOwnPropertyDescriptor, since we just want a boolean result)

Otherwise I worry this might send correct browsers down the wrong path. baseURI should never be an own-property of `document`... I guess old Safari was broken. According to the spec, it should be on Node.prototype: https://dom.spec.whatwg.org/#interface-node

**Comment by jmesserly** [comment]
added one comment, but overall I like the fix. thanks for tracking that down.

**Comment by mereskin** [comment]
screen shot 2015-02-11 at 11 56 14 am

I amended commit to keep `!doc.baseURI`, but `Object.hasOwnProperty(doc, 'baseURI')` is false, so I'd rather leave it as it is.

**Comment by jmesserly** [comment]
oh wow, good idea to check that. yeah I guess since the accessor is busted, it's possible for getOwn* and hasOwn* to be different. Crazy. Anyway this is great, going to merge. Cheers!

**Comment by mereskin** [comment]
Thank you!
Do you know when is the planned date of a new release?
We happened to use the polyfill in production, and some of our clients await for the fix.

**Comment by garlicnation** [comment]
0.5.5 just came out. I'm continuing to work on test infrastructure/CI part-time, but hopefully during march we'll have continuous delivery of webcomponentsjs so that every merged pull request fires off a release.

**Comment by mereskin** [comment]
Thank you, great news!
